# Generated by Django 4.1.7 on 2023-02-27 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard_Details_Model',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=500)),
            ],
            options={
                'db_table': 'user_details',
            },
        ),
    ]
