# Generated by Django 4.1.7 on 2023-02-28 11:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user_dashboard_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_Post_Model',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('message', models.CharField(max_length=900)),
                ('usr_fk', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='user_dashboard_app.dashboard_details_model')),
            ],
            options={
                'db_table': 'user_posts',
            },
        ),
    ]
